////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  1998-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_GRAPHICS_INC__
#define __PALM_GRAPHICS_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_OS_INC__
#   include <PalmOS.inc>
#endif

#ifndef __RECT_INC__
#   include <Point.inc>
#endif

#ifndef __SIZE_INC__
#   include <Size.inc>
#endif

#ifndef __RECT_INC__
#   include <Rect.inc>
#endif

#ifndef __PALM_BITMAP_INC__
#   include <PalmBitmap.inc>
#endif

#ifndef __PALM_WINDOW_INC__
#   include <PalmWindow.inc>
#endif

#ifndef __PALM_GRAPHICS_H__
#   include <PalmGraphics.hpp>
#endif

#ifndef __PALM_GRAPHICS_INL__
#   include <PalmGraphics.inl>
#endif

#endif // __PALM_GRAPHICS_INC__
////////////////////////////////////////////////////////////////////////////////////////
