////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  1989-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_HTTP_URL_INC__
#define __PALM_HTTP_URL_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_URL_INC__
#   include <PalmURL.inc>
#endif

#ifndef __PALM_HTTP_URL_H__
#   include <PalmHTTPURL.hpp>
#endif

#ifndef __PALM_HTTP_URL_INL__
#   include <PalmHTTPURL.inl>
#endif

#endif // __PALM_HTTP_URL_INC__
////////////////////////////////////////////////////////////////////////////////////////
