////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  Copyright © 1989-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_SOCKET_MODULE_INC__
#define __PALM_SOCKET_MODULE_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_OS_INC__
#   include <PalmOS.inc>
#endif

#ifndef __PALM_ERROR_INC__
#   include <PalmError.inc>
#endif

#ifndef __PALM_MODULE_INC__
#   include <PalmModule.inc>
#endif

#ifndef __PALM_SOCKET_MODULE_H__
#   include <PalmSocketModule.hpp>
#endif

#ifndef __PALM_SOCKET_MODULE_INL__
#   include <PalmSocketModule.inl>
#endif

#endif // __PALM_SOCKET_MODULE_INC__
////////////////////////////////////////////////////////////////////////////////////////
