////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  Copyright © 1989-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_LIST_INC__
#define __PALM_LIST_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_OS_INC__
#   include <PalmOS.inc>
#endif

#ifndef __PALM_ERROR_INC__
#   include <PalmError.inc>
#endif

#ifndef __PALM_CONTROL_INC__
#   include <PalmControl.inc>
#endif

#ifndef __PALM_LIST_H__
#   include <PalmList.hpp>
#endif

#ifndef __PALM_LIST_INL__
#   include <PalmList.inl>
#endif

#endif // __PALM_LIST_INC__
////////////////////////////////////////////////////////////////////////////////////////
