////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  1998-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_IPV4_ADDRESS_INC__
#define __PALM_IPV4_ADDRESS_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_OS_INC__
#   include <PalmOS.inc>
#endif

#ifndef __PALM_ERROR_INC__
#   include <PalmError.inc>
#endif

#ifndef __PALM_SOCKET_MODULE_INC__
#   include <PalmSocketModule.inc>
#endif

#ifndef __PALM_URL_INC__
#   include <PalmURL.inc>
#endif

#ifndef __PALM_IPV4_ADDRESS_H__
#   include <PalmIPv4.hpp>
#endif

#ifndef __PALM_IPV4_ADDRESS_INL__
#   include <PalmIPv4.inl>
#endif

#endif // __PALM_IPV4_ADDRESS_INC__
////////////////////////////////////////////////////////////////////////////////////////
