////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  1989-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_DATAGRAM_SOCKET_INC__
#define __PALM_DATAGRAM_SOCKET_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_OS_INC__
#   include <PalmOS.inc>
#endif

#ifndef __PALM_ERROR_INC__
#   include <PalmError.inc>
#endif

#ifndef __PALM_SOCKET_INC__
#   include <PalmSocket.inc>
#endif

#ifndef __PALM_DATAGRAM_SOCKET_H__
#   include <PalmDatagramSocket.hpp>
#endif

#ifndef __PALM_DATAGRAM_SOCKET_INL__
#   include <PalmDatagramSocket.inl>
#endif

#endif // __PALM_DATAGRAM_SOCKET_INC__
////////////////////////////////////////////////////////////////////////////////////////
