////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  1998-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_FORM_INC__
#define __PALM_FORM_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_OS_INC__
#   include <PalmOS.inc>
#endif

#ifndef __RECT_INC__
#   include <Point.inc>
#endif

#ifndef __SIZE_INC__
#   include <Size.inc>
#endif

#ifndef __RECT_INC__
#   include <Rect.inc>
#endif

#ifndef __PALM_EVENT_INC__
#   include <PalmEvent.inc>
#endif

#ifndef __PALM_GADGET_INC__
#   include <PalmGadget.inc>
#endif

#ifndef __PALM_FORM_H__
#   include <PalmForm.hpp>
#endif

#ifndef __PALM_FORM_INL__
#   include <PalmForm.inl>
#endif

#endif // __PALM_FORM_INC__
////////////////////////////////////////////////////////////////////////////////////////
