////////////////////////////////////////////////////////////////////////////////////////
//......................................................................................
//  This is a part of AI Library [Arthur's Interfaces Library].                        .
//  Copyright © 1989-2001 Arthur Amshukov                                              .
//......................................................................................
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND         .
//  DO NOT REMOVE MY NAME AND THIS NOTICE FROM THE SOURCE                              .
//......................................................................................
////////////////////////////////////////////////////////////////////////////////////////
#ifndef __PALM_FIELD_INC__
#define __PALM_FIELD_INC__

#pragma once

#ifndef __AIL_H__
#   include <ail.hpp>
#endif

#ifndef __PALM_OS_INC__
#   include <PalmOS.inc>
#endif

#ifndef __RECT_INC__
#   include <Point.inc>
#endif

#ifndef __SIZE_INC__
#   include <Size.inc>
#endif

#ifndef __RECT_INC__
#   include <Rect.inc>
#endif

#ifndef __PALM_CONTROL_INC__
#   include <PalmControl.inc>
#endif

#ifndef __PALM_FIELD_H__
#   include <PalmField.hpp>
#endif

#ifndef __PALM_FIELD_INL__
#   include <PalmField.inl>
#endif

#endif // __PALM_FIELD_INC__
////////////////////////////////////////////////////////////////////////////////////////
